### PR TITLE
Bump hermit-abi to 0.3.0 and don't restrict hermit-abi architectures

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Comment by stlankes** [comment]
At link to a discussion. rust-lang/rust#107405

**Comment by stlankes** [comment]
Currently not, but maybe in the future.

**Review by seanmonstar — APPROVED** [review]

**Comment by stlankes** [comment]
Thanks for the support!

**Comment by jpmckinney** [comment]
I would love a release with this commit - currently getting `clippy::multiple-crate-versions` warnings because other crates use the newer version. 🙏

**Comment by stlankes** [comment]
Which one? Atty isn't longer maintained and I am not able to remove the dependency to hermit-abi-0.1

**Comment by jpmckinney** [comment]
The bump of hermit-abi to 0.3.0.

**Comment by LingMan** [comment]
@seanmonstar Could you make a release with this? `num_cpus` is currently the only crate in my dependency trees pulling in `hermit-abi` 0.2. I'd like to get rid of the duplicates.

**Comment by seanmonstar** [comment]
Published https://github.com/seanmonstar/num_cpus/releases/tag/v1.16.0 just now.

**Comment by LingMan** [comment]
Awesome, thank you.

**Pull request merged**
