### PR TITLE
Add support for Fuchsia.

### PR DESCRIPTION
**Pull request by antiagainst**
As some background, [Fuchsia](https://en.wikipedia.org/wiki/Google_Fuchsia) is a new operating system [under development](https://github.com/fuchsia-mirror) by Google. It is based on a new microkernel called [Magenta](https://github.com/fuchsia-mirror/magenta).

Used for `nproc` in coreutils.

ref https://github.com/uutils/coreutils/issues/999

cc @raphlinus

### CODE REVIEW

**Comment by seanmonstar** [comment]
@raphlinus do you mean for that option to exist in this crate, or in Fuchsia?

**Comment by raphlinus** [comment]
@seanmonstar Sorry to be confusing. I meant it's too bad such a thing doesn't exist in Rust's libc or stdlib, so that individual users of the feature don't have to figure out at a fine grain which platforms support it.

**Comment by seanmonstar** [comment]
@raphlinus ah, it seems that for all intents and purposes this crate is that config :)

**Comment by antiagainst** [comment]
Thanks @seanmonstar! Any chance pushing out a new release to crates.io sometime soon so that [uutils/coreutils](https://github.com/uutils/coreutils) can be updated?

**Comment by seanmonstar** [comment]
Yep, in the process of publishing. Seems my nightly cargo has an SSL bug, but once I revert there will be v1.2.0 published.

**Comment by antiagainst** [comment]
Cool! Thanks a lot!

**Comment by seanmonstar** [comment]
Done!

**Pull request merged**
