### PR TITLE
Support AIX operating system

### PR DESCRIPTION
**Pull request by ecnelises**
The physical CPU number detection is done by dividing logical CPU number with SMT mode.

### CODE REVIEW

**Comment by ecnelises** [comment]
Gently remind the owner for comments... @seanmonstar

**Comment by ecnelises** [comment]
Any comments..? @seanmonstar

**Comment by seanmonstar** [comment]
As it's a Tier 3 target for rustc, I'm fine with adding here without tests, and there's no guarantee it works, and it can be removed later on if the OS stops existing.

**Comment by ecnelises** [comment]
Thanks!

**Pull request merged**
