### PR TITLE
fix: optional fields for /proc/self/mountinfo

### PR DESCRIPTION
**Pull request by flisky**
according to <https://man7.org/linux/man-pages/man5/proc.5.html>,
`/proc/[pid]/mountinfo` could have zero or more
fields and separated by a single hyphen.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks for the PR! Do you have an example that this fixes, to help me understand the reason for the code changes?

**Comment by flisky** [comment]
Thanks for investigating this!

```
       /proc/[pid]/mountinfo (since Linux 2.6.26)
              ...
              The file contains lines of the form:

              36 35 98:0 /mnt1 /mnt2 rw,noatime master:1 - ext3 /dev/root rw,errors=continue
              (1)(2)(3)   (4)   (5)      (6)      (7)   (8) (9)   (10)         (11)
```
On our k8s instance, the `mountinfo` has none optional fields (part `(7)` in above form).
(Actually, it is sentenced as [a private mount](https://man7.org/linux/man-pages/man7/mount_namespaces.7.html#:~:text=If%20none,a%20private%20mount))

However,  it's asked for exactly one optional field in the current implementation (`shared:7` in [fixtures](https://github.com/seanmonstar/num_cpus/blob/a49a20370473a3bdbb50e25ed1cb810bc96f0982/fixtures/cgroups/proc/cgroups/mountinfo#L7)).

**Comment by seanmonstar** [comment]
Oh ok, cool. Speaking of, can this make use of the existing fixtures (or add a new one if needed) to make some tests to catch this fix?

**Comment by flisky** [comment]
Fixture is a bit cumbersome in this case, and I prefer some simple unittest :)

**Review by seanmonstar — APPROVED** [review]
Awesome, thank you for the tests! And now I've just realized that this repo is still setup for Travis-CI, and that's no longer free. I need to get the tests ported over to GitHub Actions...

**Comment by flisky** [comment]
#113 was merged, closing.

**Pull request closed without merging**
